services:
  postgres:
    image: postgres:17
    container_name: tdd-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=tdd_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password